[package]
name = "generator-proxy-to-anc"
version = "0.0.0"
authors = ["_astromartian"]
edition = "2018"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "0.16.0" }
cosmwasm-bignumber = "2.2.0"
cw-storage-plus = "0.8.0"
schemars = "0.8.1"
serde = { version = "1.0.125", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.24" }
cw2 = "0.8.0"
cw20 = "0.8.0"
astroport = { version = "1.0.1" }
anchor-token = {version = "0.3.0-alpha.1"}

[dev-dependencies]
cosmwasm-schema = { version = "0.16.0" }
